#-------------------------------
# General Site Settings

title: Lakshya Agarwal
logo: logo.png
email: lakshyagrwal12@gmail.com
phone: +91 8509376954

menu:
- {name: Resume, link: '/resume.pdf'}
- {name: Kaggle, link: 'https://www.kaggle.com/lakshyaag'}
- {name: GitHub, link: 'https://github.com/lakshyaag/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-131421147-1


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Lakshya Agarwal!

social:
- {icon: "ti-facebook", link: "https://fb.com/lakshyaag"}
- {icon: "ti-instagram", link: "https://www.instagram.com/lakshyaag/"}
- {icon: "ti-twitter", link: "https://www.twitter.com/lakshyaag/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Hello! I'm Lakshya, a student of Economics, currently living in Delhi, India. <br>I have a keen interest in working with publicly available data and building things that live on the Internet. I am currently looking for opportunites to apply my learning to practical scenarios and gain a wider, more holisitic understanding of various fields. 

  # About Page

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Microsoft Office, color: '#bdecf6', value: '90%'}
- {name: Data Visualization, color: '#f6d8bd', value: '80%'}
- {name: Python, color: '#fdb157', value: '70%'}
- {name: R, color: '#9473e6', value: '70%'}
- {name: Tableau, color: '#ffbcaa', value: '50%'}
- {name: Stata, color: '#c2ffaa', value: '30%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Summer Intern - NITI Aayog, icon: 'icon-1.png', date: 'Jun 2019 - Aug 2019', organization: ''}
- {name: General Secretary, icon: 'icon-3.png', date: 'Aug 2018 - Jul 2019', organization: 'Hansraj Economics Society'}

#-------------------------------
# Education Section

education-title: Education
education:
- {name: B. A. (Hons. ) Economics, date: '2017-2020', organization: 'Hansraj College, University of Delhi'}
- {name: ISC (Commerce Stream), date: '2015-2017', organization: 'Don Bosco School, Siliguri'}

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/india_trade.jpg"
    url: "https://lakshyaag.shinyapps.io/IndiaTrade/"
    name: Indian Trade Dashboard
    
  - image : "assets/images/portfolio/ipl_analytics.jpg"
    url: "https://ipldash.herokuapp.com/"
    name: IPL Dashboard
    
  - image : "assets/images/portfolio/loksabha_questions.jpg"
    url: "https://lakshyaag.shinyapps.io/LokSabhaQuestions/"
    name: 17th Lok Sabha Questions
    
  - image : "assets/images/portfolio/crime_dash.jpg"
    url: "https://lakshyaag.shinyapps.io/CrimeInIndia/"
    name: Indian Crime Dashboard
    
  - image : "assets/images/portfolio/kicc.jpg"
    url: "#"
    name: KPMG Innovation and Collaboration Challenge 2018

    image: "assets/images/portfolio/digital_payments.jpg"
    url: "https://drive.google.com/file/d/1se_3lHtggaE6MW0IMmJB3h-p-LqWIKrA/view?usp=sharing"
    name: Digital Payments in India


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: lakshyagrwal12@gmail.com